//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_unigis_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_zonas
    {
        public int id { get; set; }
        public string descripcion { get; set; }
    }
}
