//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_unigis_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class punto_venta
    {
        public int Id { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Venta { get; set; }
        public Nullable<int> Zona { get; set; }

        public virtual ctl_zonas DetalleZonas { get; set; }
    }
}
