//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_unigis_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class test_unigis_dbaEntities : DbContext
    {
        public test_unigis_dbaEntities()
            : base("name=test_unigis_dbaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ctl_zonas> ctl_zonas { get; set; }
        public virtual DbSet<punto_venta> punto_venta { get; set; }
    
        public virtual ObjectResult<sp_obtiene_total_ventas_Result> sp_obtiene_total_ventas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtiene_total_ventas_Result>("sp_obtiene_total_ventas");
        }
    }
}
